// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhu8Wb50alMRXTMfqyIw9T9hZavV9aQA0',
    appId: '1:599233465737:web:3bc852f3ace98ccc582558',
    messagingSenderId: '599233465737',
    projectId: 'flutter-chat-app-c1d37',
    authDomain: 'flutter-chat-app-c1d37.firebaseapp.com',
    storageBucket: 'flutter-chat-app-c1d37.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFXb8a9B60e8m3hy1Tbmh3JVferrB9z4Y',
    appId: '1:599233465737:android:8ce731365bd95fca582558',
    messagingSenderId: '599233465737',
    projectId: 'flutter-chat-app-c1d37',
    storageBucket: 'flutter-chat-app-c1d37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKZ-0XU5wCTHeoJLQC41CiIKjKFJlCMRw',
    appId: '1:599233465737:ios:2da01512abf220b5582558',
    messagingSenderId: '599233465737',
    projectId: 'flutter-chat-app-c1d37',
    storageBucket: 'flutter-chat-app-c1d37.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKZ-0XU5wCTHeoJLQC41CiIKjKFJlCMRw',
    appId: '1:599233465737:ios:dca467915624f9c9582558',
    messagingSenderId: '599233465737',
    projectId: 'flutter-chat-app-c1d37',
    storageBucket: 'flutter-chat-app-c1d37.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
